accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name="signup"),
    url(r'^login/', views.loginview, name="login"),

]

clubs/urls.py
from django.conf.urls import url
from . import views

app_name = 'clubs'

urlpatterns = [
    url(r'^create/', views.create, name="create"),
    url(r'^listing/', views.listing, name="listing"),
    url(r'^listingcounties/', views.listingCounties, name="listingcounties")

]

shareit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from clubs import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^clubs/', include('clubs.urls')),
    url(r'^$', views.home, name="home")
]

clubs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='media/')
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User)
    body = models.TextField()

class Club(models.Model):
    name = models.CharField(max_length= 200)
    county = models.CharField(max_length= 200)
    location = models.URLField()
    province = models.CharField(max_length=50)
    
    def __str__(self):
        return self.county + " - " + self.name
        
    

posts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
# Create your views here.

def signup(request):
    if request.method =='POST':
        if request.POST['password1'] == request.POST['password2']:

            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/signup.html', {'error':'Username already taken.'})
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'],password=request.POST['password1'])
                login(request, user)
                return render(request, 'accounts/signup.html')

        else:
            return render(request, 'accounts/signup.html', {'error':'Passwords don\'t match.'})
    else:
        return render(request, 'accounts/signup.html')


def loginview(request):
    if request.method =='POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                    return redirect(request.POST['next'])
            return render(request, 'accounts/login.html', {'error':'Login successful!'})
        else:
            return render(request, 'accounts/login.html', {'error':'No valid information.'})
    else:
        return render(request, 'accounts/login.html')

clubs/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post , Club
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.

@login_required
def create(request):
    if request.method =='POST':
        if request.POST['title'] and request.POST['url']:
            post = models.Post()
            post.title = request.POST['title']
            post.url = request.POST['url']
            post.pub_date = timezone.datetime.now()
            post.author = request.user
            post.save()
            return render(request, 'clubs/home.html')
        else:
            return render(request, 'clubs/create.html', {'error':'Sorry, You need to have both a title and a Url to create a post.'})

    else:
        return render(request, 'clubs/create.html')

def home(request):
    try:
        del request.session['query']
    except: 
        query = ""
        
    return render(request, 'clubs/home.html')
    
def listingCounties(request):
    try:
        if request.method =='POST':
            
            query = ""            
            query = request.POST.get('County', "")
            request.session['query'] = query
            clubs_list = Club.objects.filter(county__icontains= request.session['query'])
            
        else:
            
            clubs_list = Club.objects.filter(county__icontains= request.session['query'])
            
    except KeyError:
        
        query = ""
        clubs_list = Club.objects.order_by('name')

        
    paginator = Paginator(clubs_list, 15)
    page = request.GET.get('page')
    
    try:
        
        clubs = paginator.object_list.order_by('name')
        clubs = paginator.page(page)
        
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        
        clubs = paginator.object_list.order_by('name')
        clubs = paginator.page(1)
        
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        
        clubs = paginator.object_list.order_by('name')
        clubs = paginator.page(paginator.num_pages)
        
    except query:
        
        clubs = paginator.object_list.order_by('name')
        clubs = paginator.page()

    return render(request, 'clubs/county.html', {'clubs':clubs})
    

    

def listing(request):
    try:
        if request.method =='POST':
            
            query = request.POST.get('search_clubs', "")
            request.session['query'] = query
            clubs_list = Club.objects.filter(name__icontains= request.session['query'])
            
        else:
            
            clubs_list = Club.objects.filter(name__icontains= request.session['query'])
            
    except KeyError:
        
        query = ""
        clubs_list = Club.objects.order_by('name')

        
    paginator = Paginator(clubs_list, 15)
    page = request.GET.get('page')
    
    try:
        
        clubs = paginator.object_list.order_by('name')
        clubs = paginator.page(page)
        
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        
        clubs = paginator.object_list.order_by('name')
        clubs = paginator.page(1)
        
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        
        clubs = paginator.object_list.order_by('name')
        clubs = paginator.page(paginator.num_pages)
        
    except query:
        
        clubs = paginator.object_list.order_by('name')
        clubs = paginator.page()

    return render(request, 'clubs/club.html', {'clubs':clubs})
    

posts/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}



{% if error %}
{{error}}
<br/><br/>
{% endif %}

<div class="container">
<form method="post" action="{% url 'accounts:login' %}">
  {% csrf_token %}
<h1>Login!</h1>

  {% if request.GET.next %}
  <input type="hidden" name="next" value={{ request.GET.next }}/>
  {% endif %}
  Username:
  <br/>
  <input type="text" name="username" />
  <br/>
  Password:
  <br/>
  <input type="password" name="password" />
  <br/>
  <input type="submit" value="Login"/>

</form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}



{% if error %}
{{error}}
<br/><br/>
{% endif %}

<div class="container">
<form method="post" action="{% url 'accounts:signup' %}">
<h1>Sign Up!</h1>
  {% csrf_token %}

  Username:
  <br/>
  <input type="text" name="username" />
  <br/>
  Password:
  <br/>
  <input type="password" name="password1" />
  <br/>
  Confirm Password:
  <br/>
  <input type="password" name="password2" />
  <br/>
  <input type="submit" value="Sign Up!"/>

</form>
</div>

{% endblock %}

clubs/templates/clubs/club.html
{% extends 'base.html' %}
{% block content %}
<div class="container text-center">
<h3><a href = "{% url 'home' %}">Home</a></h3>
	<form action = "{% url 'clubs:listing' %}" method="post">
	{% csrf_token %}	
		<div class="container">
			<div class="row">
			   	<div id="custom-search-input">
					<div class="input-group col-md-12">
						<input type="text" name="search_clubs" id ="search_clubs" class="  search-query form-control" placeholder="Search by Name" />
						<span class="input-group-btn">
							<button class="btn btn-danger" type="button">
						<span class=" glyphicon glyphicon-search"></span>
							</button>
						</span>
						
					</div>
				</div>
			</div>
		</div>
	</form>

		{% for clubs in clubs %}
		<div class="container1 text-center" >
		<table>
		<tr>
			<th>{{ clubs.name }} - {{ clubs.county }}</th>
			<td>
			<a href="{{ clubs.location }}"><button type="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-map-marker"></span> Locate</button></a>
			</td>
		</tr>
		</table>
		</div>
		{% endfor %}
	
</div>

<div class="container text-center">
	<nav aria-label="Page navigation" >
		<ul class="pagination">
			<li>
				<a href="?page={{ clubs.1 }}" aria-label="Previous">
					<span aria-hidden="true">&laquo;</span>
				</a>
					</li>
					{% if clubs.has_previous %}
					<li><a href="?page={{ clubs.previous_page_number }}">Previous</a></li>
					{% endif %}
					<li><a class="current" href="?page={{ clubs.number }}">Page {{ clubs.number }} of {{ clubs.paginator.num_pages }}</a></li>
					{% if clubs.has_next %}
					<li><a href="?page={{ clubs.next_page_number }}">Next</a></li>
					{% endif %}
					<li>
				<a href="?page={{ clubs.paginator.num_pages }}" aria-label="Next">
					<span aria-hidden="true">&raquo;</span>
				</a>
			</li>
		</ul>
	</nav>
</div>

<br>
{% endblock %}

clubs/templates/clubs/county.html
{% extends 'base.html' %}

{% block content %}
<div class="container text-center">
<h1><a href = "{% url 'home' %}"> All Clubs </a></h1>

<form action = "{% url 'clubs:listingcounties' %}" method="post">
{% csrf_token %}
	
	<div class="container">
		<div class="row">
		   	<div id="custom-search-input">
				<div class="input-group col-md-12">
					<input type="text" name="County" id ="County" class="  search-query form-control" placeholder="Search by Name" />
					<span class="input-group-btn">
						<button class="btn btn-danger" type="button">
					<span class=" glyphicon glyphicon-search"></span>
						</button>
					</span>
					
				</div>
			</div>
		</div>
	</div>	
</form>
		{% for clubs in clubs %}
		<div class="container1 text-center" style="margin:0 auto;">
		<table>
		<tr>
			<th>{{ clubs.county }} - {{ clubs.name }}</th>
			<td>
			<a href="{{ clubs.location }}"><button type="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-map-marker"></span> Locate</button></a>
			</td>
		</tr>
		{% endfor %}
		</div>
			
	
</div>

<div class="container text-center">
<nav aria-label="Page navigation">
	<ul class="pagination">
		<li>
			<a href="?page={{ clubs.1 }}" aria-label="Previous">
				<span aria-hidden="true">&laquo;</span>
			</a>
				</li>
				{% if clubs.has_previous %}
				<li><a href="?page={{ clubs.previous_page_number }}">Previous</a></li>
				{% endif %}
				<li><a class="current" href="?page={{ clubs.number }}">Page {{ clubs.number }} of {{ clubs.paginator.num_pages }}</a></li>
				{% if clubs.has_next %}
				<li><a href="?page={{ clubs.next_page_number }}">Next</a></li>
				{% endif %}
				<li>
			<a href="?page={{ clubs.paginator.num_pages }}" aria-label="Next">
				<span aria-hidden="true">&raquo;</span>
			</a>
		</li>
	</ul>
</nav>
<br>

</div>



{% endblock %}

clubs/templates/clubs/create.html
{% extends 'base.html' %}

{% block content %}

<h1>New Post</h1>

{% if error %}
{{ error }}
<br />
<br />
{% endif %}

<form method="POST" action="{% url 'clubs:create' %}">
  {% csrf_token %}

  Title:
  <br />
  <input type="text" name="title" />
  <br />
  URL:
  <br />
  <input type="text" name="url" />
  <br />
  <br />
  <input class="btn btn-primary" type="submit" value="Post">
</form>
{% endblock %}

clubs/templates/clubs/home.html
{% extends 'base.html' %}

{% block content %}

<!-- <a href="{% url 'clubs:create' %}">New Post</a> -->


<form action = "{% url 'clubs:listing' %}" method="post">
<div class="container1 text-center" >
	<h4>Search for Clubs by Name</h4>
	{% csrf_token %}
	<input type="text" name="search_clubs" id ="search_clubs" placeholder="Search by name.."></input>
	<br>
		<button class="btn btn-primary btn-default btn" type="submit" >Search</button>
		<button class="btn btn-default btn" action="{% url 'home' %}" >Reset</button>
	<br>
</form>
</div>



<form method="POST" action="{% url 'clubs:listingcounties' %}">
	<div class="container text-center">
	{% csrf_token %}
	
	<h4>Search for Clubs by County</h4>
		<select name="County">
			<option name="County" id= "County" value="Antrim">Antrim</option>
			<option name="County" id= "County" value="Armagh">Armagh</option>
			<option name="County" id= "County" value="Carlow">Carlow</option>
			<option name="County" id= "County" value="Cavan">Cavan</option>
			<option name="County" id= "County" value="Clare">Clare</option>
			<option name="County" id= "County" value="Cork">Cork</option>
			<option name="County" id= "County" value="Donegal">Donegal</option>
			<option name="County" id= "County" value="Down">Down</option>
			<option name="County" id= "County" value="Dublin">Dublin</option>
			<option name="County" id= "County" value="Fermanagh">Fermanagh</option>
			<option name="County" id= "County" value="Dublin">Dublin</option>
			<option name="County" id= "County" value="Galway">Galway</option>
			<option name="County" id= "County" value="Kerry">Kerry</option>
			<option name="County" id= "County" value="Kildare">Kildare</option>
			<option name="County" id= "County" value="Kilkenny">Kilkenny</option>
			<option name="County" id= "County" value="Laois">Laois</option>
			<option name="County" id= "County" value="Leitrim">Leitrim</option>
			<option name="County" id= "County" value="Limerick">Limerick</option>
			<option name="County" id= "County" value="Derry">Derry</option>
			<option name="County" id= "County" value="Longford">Longford</option>
			<option name="County" id= "County" value="Louth">Louth</option>
			<option name="County" id= "County" value="Mayo">Mayo</option>
			<option name="County" id= "County" value="Meath">Meath</option>
			<option name="County" id= "County" value="Monaghan">Monaghan</option>
			<option name="County" id= "County" value="Offaly">Offaly</option>
			<option name="County" id= "County" value="Roscommon">Roscommon</option>
			<option name="County" id= "County" value="Sligo">Sligo</option>
			<option name="County" id= "County" value="South Tipperary">Tipperary</option>
			<option name="County" id= "County" value="Tyrone">Tyrone</option>
			<option name="County" id= "County" value="Waterford">Waterford</option>
			<option name="County" id= "County" value="Westmeath">Westmeath</option>
			<option name="County" id= "County" value="Wexford">Wexford</option>
			<option name="County" id= "County" value="Wicklow">Wicklow</option>
		</select>
		<br>
		<input class="btn btn-primary btn-default btn" type="submit">
	</div>
</form>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>GAA Pitch Finder</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<style>
	.jumbotron {
			background-color: #289949;
			color: #fff;
	}
	</style>
	<style>
	.navbar1 { 
		background-color: #999999;
		color: #ffffff;
	}
	table {
		width: 100%;
		border-collapse: collapse;
	}
	td {
		text-align: right;
		padding: 8px;
	}
	th {
		text-align: left;
		padding: 8px;
	}
	
	

	#custom-search-input {
			margin:0;
			margin-top: 10px;
			padding: 0;
		}
	 
		#custom-search-input .search-query {
			padding-right: 3px;
			padding-right: 4px \9;
			padding-left: 3px;
			padding-left: 4px \9;
			/* IE7-8 doesn't have border-radius, so don't indent the padding */
	 
			margin-bottom: 0;
			-webkit-border-radius: 3px;
			-moz-border-radius: 3px;
			border-radius: 3px;
		}
	 
		#custom-search-input button {
			border: 0;
			background: none;
			/** belows styles are working good */
			padding: 2px 5px;
			margin-top: 2px;
			position: relative;
			left: -28px;
			/* IE7-8 doesn't have border-radius, so don't indent the padding */
			margin-bottom: 0;
			-webkit-border-radius: 3px;
			-moz-border-radius: 3px;
			border-radius: 3px;
			color:#D9230F;
		}
	 
		.search-query:focus + button {
			z-index: 3;   
		}
	
	</style>
</head>

<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>                        
			</button>
			<a class="navbar-brand" href="{% url 'home' %}">GPF</a>
		</div>
		<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="{% url 'home' %}">HOME</a></li>
				<li><a href="{% url 'accounts:login' %}">LOGIN</a></li>
				<li><a href="{% url 'accounts:signup' %}">SIGNUP</a></li>
				<li><a href="#">YOUR PAGE</a></li>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">MORE
					<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="#">Login</a></li>
						<li><a href="#">Signup</a></li>
						<li><a href="#">About</a></li> 
					</ul>
				</li>
				<li><a href="#"><span class="glyphicon glyphicon-search"></span></a></li>
			</ul>
		</div>
	</div>
</nav>

<div class="jumbotron text-center" >
<br>
	<h2>GAA Pitch Finder</h2> 
	<p>Find your Local Club!</p> 
</div>

{% block content %}
{% endblock %}

<br>
<br>

<nav class="navbar1 navbar-default navbar-fixed-bottom text-center">
  	<p>Martin Quinn</p> 
	<a href="https://github.com/MartinQuinn">GitHub</a>
</nav>